version: '2.1'
services:
  frontend:
    network_mode: host
    build:
      context: ../../
      dockerfile: docker/e2e-tests/Dockerfile-frontend
    env_file:
      - ../../.env
    environment:
      REACT_APP_AUTH_REDIRECT_URL: http://travela-docker.andela.com:3000
      REACT_APP_API_URL: http://travela-docker.andela.com:5000/api/v1
    command: >
      bash -c "echo '127.0.0.1 travela-docker.andela.com' >> /etc/hosts &&
      yarn start"
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -s travela-docker.andela.com:3000']
      interval: 10s
      timeout: 10s
      retries: 5
  backend:
    network_mode: host
    build:
      context: $BACKEND
      dockerfile: $PWD/docker/e2e-tests/Dockerfile-backend
    env_file:
      - $BACKEND/.env
    environment:
      REDIRECT_URL: http://travela-docker.andela.com:3000
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/travela
      NODE_ENV: test
    command: >
        bash -c "echo '127.0.0.1 travela-docker.andela.com' >> /etc/hosts &&
        yarn db:migrate &&
        yarn db:seed:e2e &&
        yarn start:dev"
    healthcheck:
      test: ['CMD-SHELL', 'curl -s travela-docker.andela.com:5000/api/v1/_healthz']
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
  database:
    network_mode: host
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travela
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
