apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  containers:
  - name: travela-frontend-agent
    image: eu.gcr.io/andela-learning/jenkins-travela-frontend
    resources:
      requests:
        cpu: "2000m"
        memory: "2Gi"
      limits:
        cpu: "2000m"
        memory: "2Gi"
    command:
    - cat
    tty: true
    env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
  - name: dind
    image: docker:18.05-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  volumes:
  - name: dind-storage
    emptyDir: {}
