export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_FAILURE = 'SET_CURRENT_USER_FAILURE';

// REQUESTS
export const FETCH_USER_REQUESTS = 'FETCH_USER_REQUESTS';
export const FETCH_USER_REQUESTS_SUCCESS = 'FETCH_USER_REQUESTS_SUCCESS';
export const FETCH_USER_REQUESTS_FAILURE = 'FETCH_USER_REQUESTS_FAILURE';
export const CREATE_NEW_REQUEST = 'CREATE_NEW_REQUEST';
export const CREATE_NEW_REQUEST_SUCCESS = 'CREATE_NEW_REQUEST_SUCCESS';
export const CREATE_NEW_REQUEST_FAILURE = 'CREATE_NEW_REQUEST_FAILURE';
export const FETCH_EDIT_REQUEST_SUCCESS = 'FETCH_EDIT_REQUEST_SUCCESS';
export const FETCH_EDIT_REQUEST_FAILURE = 'FETCH_EDIT_REQUEST_FAILURE';

// USERS
export const POST_USER_DATA = 'POST_USER_DATA';
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';
export const POST_USER_DATA_FAILURE = 'POST_USER_DATA_FAILURE';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

// ROLES
export const GET_ROLE_DATA = 'GET_ROLE_DATA';
export const GET_ROLE_DATA_SUCCESS = 'GET_ROLE_DATA_SUCCESS';
export const GET_ROLE_DATA_FAILURE = 'GET_ROLE_DATA_FAILURE';
export const PUT_ROLE_DATA = 'PUT_ROLE_DATA';
export const PUT_ROLE_DATA_SUCCESS = 'PUT_ROLE_DATA_SUCCESS';
export const PUT_ROLE_DATA_FAILURE = 'PUT_ROLE_DATA_FAILURE';
export const FETCH_ROLE_USERS = 'FETCH_ROLE_USERS';
export const FETCH_ROLE_USERS_SUCCESS = 'FETCH_ROLE_USERS_SUCCESS';
export const FETCH_ROLE_USERS_FAILURE = 'FETCH_ROLE_USERS_FAILURE';
export const DELETE_USER_ROLE = 'DELETE_USER_ROLE';
export const DELETE_USER_ROLE_SUCCESS = 'DELETE_USER_ROLE_SUCCESS';
export const DELETE_USER_ROLE_FAILURE = 'DELETE_USER_ROLE_FAILURE';
export const SHOW_DELETE_ROLE_MODAL = 'SHOW_DELETE_ROLE_MODAL';
export const HIDE_DELETE_ROLE_MODAL = 'HIDE_DELETE_ROLE_MODAL';
export const ADD_ROLE = 'ADD_ROLE';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const ADD_ROLE_FAILURE = 'ADD_ROLE_FAILURE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE';
export const UPDATE_BUDGET_CHECKER = 'UPDATE_BUDGET_CHECKER';
export const UPDATE_BUDGET_CHECKER_SUCCESS = 'UPDATE_BUDGET_CHECKER_SUCCESS';
export const UPDATE_BUDGET_CHECKER_FAILURE = 'UPDATE_BUDGET_CHECKER_FAILURE';

// REQUEST DETAILS
export const FETCH_USER_REQUEST_DETAILS = 'FETCH_USER_REQUEST_DETAILS';
export const FETCH_USER_REQUEST_DETAILS_SUCCESS =
  'FETCH_USER_REQUEST_DETAILS_SUCCESS';
export const FETCH_USER_REQUEST_DETAILS_FAILURE =
  'FETCH_USER_REQUEST_DETAILS_FAILURE';

// EDIT REQUEST
export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_REQUEST_SUCCESS = 'EDIT_REQUEST_SUCCESS';
export const EDIT_REQUEST_FAILURE = 'EDIT_REQUEST_FAILURE';
export const FETCH_EDIT_REQUEST = 'FETCH_EDIT_REQUEST';

// DELETE REQUEST
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_FAILURE = 'DELETE_REQUEST_FAILURE';

// FETCH OCCUPATIONS
export const FETCH_OCCUPATIONS = 'FETCH_OCCUPATIONS';
export const FETCH_OCCUPATIONS_SUCCESS = 'FETCH_OCCUPATIONS_SUCCESS';
export const FETCH_OCCUPATIONS_FAILURE = 'FETCH_OCCUPATIONS_FAILURE';

//COMMENTS
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

// APPROVALS
export const FETCH_USER_APPROVALS = 'FETCH_USER_APPROVALS';
export const FETCH_USER_APPROVALS_SUCCESS = 'FETCH_USER_APPROVALS_SUCCESS';
export const FETCH_USER_APPROVALS_FAILURE = 'FETCH_USER_APPROVALS_FAILURE';

// Approve Requests
export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS';
export const UPDATE_REQUEST_STATUS_SUCCESS = 'UPDATE_REQUEST_STATUS_SUCCESS';
export const UPDATE_REQUEST_STATUS_FAILURE = 'UPDATE_REQUEST_STATUS_FAILURE';

// User profile
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

// NOTIFICATIONS
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_FAILURE = 'ADD_NOTIFICATION_FAILURE';

// mark room as faulty
export const UPDATE_ROOM_STATE = 'UPDATE_ROOM_STATE';
export const UPDATE_ROOM_STATE_SUCCESS = 'UPDATE_ROOM_STATE_SUCCESS';

export const UPDATE_ALL_NOTIFICATIONS_STATUS =
  'UPDATE_ALL_NOTIFICATIONS_STATUS';
export const UPDATE_ALL_NOTIFICATIONS_STATUS_SUCCESS =
  'UPDATE_ALL_NOTIFICATIONS_STATUS_SUCCESS';
export const UPDATE_ALL_NOTIFICATIONS_STATUS_FAILURE =
  'UPDATE_ALL_NOTIFICATIONS_STATUS_FAILURE';

export const MARK_SINGLE_NOTIFICATION_AS_READ =
  'MARK_SINGLE_NOTIFICATION_AS_READ';
export const MARK_SINGLE_NOTIFICATION_AS_READ_SUCCESS =
  'MARK_SINGLE_NOTIFICATION_AS_READ_SUCCESS';
export const MARK_SINGLE_NOTIFICATION_AS_READ_FAILURE =
  'MARK_SINGLE_NOTIFICATION_AS_READ_FAILURE';

// ACCOMMODATION
export const CREATE_ACCOMMODATION_DATA = 'CREATE_ACCOMMODATION_DATA';
export const SAVING_ACCOMMODATION = 'SAVING_ACCOMMODATION';
export const CREATE_ACCOMMODATION_DATA_SUCCESS =
  'CREATE_ACCOMMODATION_DATA_SUCCESS';
export const CREATE_ACCOMMODATION_DATA_FAILURE =
  'CREATE_ACCOMMODATION_DATA_FAILURE';
export const EDIT_ACCOMMODATION_DATA = 'EDIT_ACCOMMODATION_DATA ';
export const EDIT_ACCOMMODATION_DATA_SUCCESS =
  'EDIT_ACCOMMODATION_DATA_SUCCESS';
export const EDIT_ACCOMMODATION_DATA_FAILURE =
  'EDIT_ACCOMMODATION_DATA_FAILURE';
export const INIT_FETCH_TIMELINE_DATA = 'INIT_FETCH_TIMELINE_DATA';
export const FETCH_TIMELINE_DATA_SUCCESS = 'FETCH_TIMELINE_DATA_SUCCESS';
export const FETCH_TIMELINE_DATA_FAILURE = 'FETCH_TIMELINE_DATA_FAILURE';
export const FETCH_ACCOMMODATION_CENTRES = 'FETCH_ACCOMMODATION_CENTRES';
export const FETCH_ACCOMMODATION_CENTRES_SUCCESS =
  'FETCH_ACCOMMODATION_CENTRES_SUCCESS';
export const FETCH_ACCOMMODATION_CENTRES_FAILURE =
  'FETCH_ACCOMMODATION_CENTRES_FAILURE';
export const DISABLE_ACCOMMODATION = 'DISABLE_ACCOMMODATION';
export const DISABLE_ACCOMMODATION_SUCCESS = 'DISABLE_ACCOMMODATION_SUCCESS';
export const DISABLE_ACCOMMODATION_FAILURE = 'DISABLE_ACCOMMODATION_FAILURE';
export const FETCH_DISABLED_ACCOMMODATION = 'FETCH_DISABLED_ACCOMMODATION';
export const FETCH_DISABLED_ACCOMMODATION_SUCCESS = 'FETCH_DISABLED_ACCOMMODATION_SUCCESS';
export const FETCH_DISABLED_ACCOMMODATION_FAILURE = 'FETCH_DISABLED_ACCOMMODATION_FAILURE';
export const RESTORE_DISABLED_ACCOMMODATION = 'RESTORE_DISABLED_ACCOMMODATION';
export const RESTORE_DISABLED_ACCOMMODATION_SUCCESS = 'RESTORE_DISABLED_ACCOMMODATION_SUCCESS';
export const RESTORE_DISABLED_ACCOMMODATION_FAILURE = 'RESTORE_DISABLED_ACCOMMODATION_FAILURE';

// TRIPS
export const UPDATE_TRIP = 'UPDATE_TRIP';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
export const UPDATE_TRIP_FAILURE = 'UPDATE_TRIP_FAILURE';
export const FETCH_TRIPS = 'FETCH_TRIPS';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIPS_FAILURE = 'FETCH_TRIPS_FAILURE';

// maintenance
export const ADD_MAINTENANCE_RECORD = 'ADD_MAINTENANCE_RECORD';
export const UPDATE_MAINTENANCE_RECORD = 'UPDATE_MAINTENANCE_RECORD';
export const UPDATE_MAINTENANCE_RECORD_SUCCESS = 'UPDATE_MAINTENANCE_RECORD_SUCCESS';
export const UPDATE_MAINTENANCE_RECORD_FAILURE = 'UPDATE_MAINTENANCE_RECORD_FAILURE';
export const DELETE_MAINTENANCE_RECORD = 'DELETE_MAINTENANCE_RECORD';
export const DELETE_MAINTENANCE_RECORD_SUCCESS = 'DELETE_MAINTENANCE_RECORD_SUCCESS';
export const DELETE_MAINTENANCE_RECORD_FAILURE = 'DELETE_MAINTENANCE_RECORD_FAILURE';

// TRAVEL CHECKLIST
export const CREATE_TRAVEL_CHECKLIST = 'CREATE_TRAVEL_CHECKLIST';
export const CREATE_TRAVEL_CHECKLIST_SUCCESS =
  'CREATE_TRAVEL_CHECKLIST_SUCCESS';
export const CREATE_TRAVEL_CHECKLIST_FAILURE =
  'CREATE_TRAVEL_CHECKLIST_FAILURE';
export const UPDATE_TRAVEL_CHECKLIST = 'UPDATE_TRAVEL_CHECKLIST';
export const UPDATE_TRAVEL_CHECKLIST_SUCCESS =
  'UPDATE_TRAVEL_CHECKLIST_SUCCESS';
export const UPDATE_TRAVEL_CHECKLIST_FAILURE =
  'UPDATE_TRAVEL_CHECKLIST_FAILURE';
export const FETCH_TRAVEL_CHECKLIST = 'FETCH_TRAVEL_CHECKLIST';
export const FETCH_TRAVEL_CHECKLIST_SUCCESS = 'FETCH_TRAVEL_CHECKLIST_SUCCESS';
export const FETCH_TRAVEL_CHECKLIST_FAILURE = 'FETCH_TRAVEL_CHECKLIST_FAILURE';
export const DELETE_TRAVEL_CHECKLIST = 'DELETE_TRAVEL_CHECKLIST';
export const DELETE_TRAVEL_CHECKLIST_SUCCESS =
  'DELETE_TRAVEL_CHECKLIST_SUCCESS';
export const DELETE_TRAVEL_CHECKLIST_FAILURE =
  'DELETE_TRAVEL_CHECKLIST_FAILURE';
export const FETCH_DELETED_CHECKLISTITEMS = 'FETCH_DELETED_CHECKLISTITEMS';
export const FETCH_DELETED_CHECKLISTITEMS_SUCCESS = 'FETCH_DELETED_CHECKLISTITEMS_SUCCESS';
export const FETCH_DELETED_CHECKLISTITEMS_FAILURE = 'FETCH_DELETED_CHECKLISTITEMS_FAILURE';
export const RESTORE_TRAVEL_CHECKLIST = 'RESTORE_TRAVEL_CHECKLIST';
export const RESTORE_TRAVEL_CHECKLIST_SUCCESS = 'RESTORE_TRAVEL_CHECKLIST_SUCCESS';
export const RESTORE_TRAVEL_CHECKLIST_FAILURE = 'RESTORE_TRAVEL_CHECKLIST_FAILURE';

// CENTERS
export const FETCH_CENTERS = 'FETCH_CENTERS';
export const FETCH_CENTERS_SUCCESS = 'FETCH_CENTERS_SUCCESS';
export const FETCH_CENTERS_FAILURE = 'FETCH_CENTERS_FAILURE';

export const UPDATE_USER_CENTER = 'UPDATE_USER_CENTERS';
export const UPDATE_USER_CENTER_SUCCESS = 'UPDATE_USER_CENTER_SUCCESS';
export const UPDATE_USER_CENTER_FAILURE = 'UPDATE_USER_CENTER_FAILURE';

// AVAILABLE ROOMS
export const FETCH_AVAILABLE_ROOMS = 'FETCH_AVAILABLE_ROOMS';
export const FETCH_AVAILABLE_ROOMS_SUCCESS = 'FETCH_AVAILABLE_ROOMS_SUCCESS';
export const FETCH_AVAILABLE_ROOMS_FAILURE = 'FETCH_AVAILABLE_ROOMS_FAILURE';

//TRIP ROOMS
export const UPDATE_TRIP_ROOM = 'UPDATE_TRIP_ROOM';
export const UPDATE_TRIP_ROOM_SUCCESS = 'UPDATE_TRIP_ROOM_SUCCESS';
export const UPDATE_TRIP_ROOM_FAILURE = 'UPDATE_TRIP_ROOM_FAILURE';

// ANALYTICS
export const FETCH_ANALYTICS = 'FETCH_ANALYTICS';
export const FETCH_ANALYTICS_SUCCESS = 'FETCH_ANALYTICS_SUCCESS';
export const FETCH_ANALYTICS_FAILURE = 'FETCH_ANALYTICS_FAILURE';
export const DOWNLOAD_ANALYTICS = 'DOWNLOAD_ANALYTICS';
export const DOWNLOAD_ANALYTICS_FAILURE = 'DOWNLOAD_ANALYTICS_FAILURE';

// DEPARTMENT TRIPS ANALYTICS
export const FETCH_DEPARTMENT_TRIPS_ANALYTICS =
'FETCH_DEPARTMENT_TRIPS_ANALYTICS';
export const FETCH_DEPARTMENT_TRIPS_ANALYTICS_FAILURE =
'FETCH_DEPARTMENT_TRIPS_ANALYTICS_FAILURE';
export const FETCH_DEPARTMENT_TRIPS_ANALYTICS_SUCCESS =
'FETCH_DEPARTMENT_TRIPS_ANALYTICS_SUCCESS';

//TRAVELREADINESS
export const FETCH_TRAVEL_READINESS = 'FETCH_TRAVEL_READINESS';
export const FETCH_TRAVEL_READINESS_SUCCESS = 'FETCH_TRAVEL_READINESS_SUCCESS';
export const FETCH_TRAVEL_READINESS_FAILURE = 'FETCH_TRAVEL_READINESS_FAILURE';
export const EXPORT_TRAVEL_READINESS = 'EXPORT_TRAVEL_READINESS';
export const EXPORT_TRAVEL_READINESS_SUCCESS =
'EXPORT_TRAVEL_READINESS_SUCCESS';
export const EXPORT_TRAVEL_READINESS_FAILURE =
  'EXPORT_TRAVEL_READINESS_FAILURE';
export const CREATE_TRAVEL_READINESS_DOCUMENT = 'CREATE_TRAVEL_READINESS_DOCUMENT';
export const CREATE_TRAVEL_READINESS_DOCUMENT_SUCCESS = 'CREATE_TRAVEL_READINESS_DOCUMENT_SUCCESS';
export const CREATE_TRAVEL_READINESS_DOCUMENT_FAILURE = 'CREATE_TRAVEL_READINESS_DOCUMENT_FAILURE';

// TRAVEL CALENDAR ANALYTICS
export const FETCH_CALENDAR_ANALYTICS = 'FETCH_CALENDAR_ANALYTICS';
export const FETCH_CALENDAR_ANALYTICS_SUCCESS =
'FETCH_CALENDAR_ANALYTICS_SUCCESS';
export const FETCH_CALENDAR_ANALYTICS_FAILURE =
'FETCH_CALENDAR_ANALYTICS_FAILURE';
export const DOWNLOAD_CALENDAR_ANALYTICS = 'DOWNLOAD_CALENDAR_ANALYTICS';
export const DOWNLOAD_CALENDAR_ANALYTICS_SUCCESS =
'DOWNLOAD_CALENDAR_ANALYTICS_SUCCESS';
export const DOWNLOAD_CALENDAR_ANALYTICS_FAILURE =
'DOWNLOAD_CALENDAR_ANALYTICS_FAILURE';

// DOCUMENTS
export const FETCH_DOCUMENTS = 'FETCH_DOCUMENTS';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'DELETE_DOCUMENT_FAILURE';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const REMOVE_DOCUMENT_FROM_EDIT = 'REMOVE_DOCUMENT_FROM_EDIT';
export const UPDATE_DOCUMENT_ON_EDIT = 'UPDATE_DOCUMENT_ON_EDIT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const UPDATE_DOCUMENT_FAILURE = 'UPDATE_DOCUMENT_FAILURE';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_FAILURE = 'CREATE_DOCUMENT_FAILURE';
export const DOWNLOAD_DOCUMENTS = 'DOWNLOAD_DOCUMENTS';
export const DOWNLOAD_DOCUMENTS_SUCCESS = 'DOWNLOAD_DOCUMENTS_SUCCESS';
export const DOWNLOAD_DOCUMENTS_FAILURE = 'DOWNLOAD_DOCUMENTS_FAILURE';
export const PASSPORT_TRAVEL_READINESS_DOCUMENT_SCAN = 'PASSPORT_TRAVEL_READINESS_DOCUMENT_SCAN';
export const PASSPORT_TRAVEL_READINESS_DOCUMENT_SCAN_SUCCESS = 'PASSPORT_TRAVEL_READINESS_DOCUMENT_SCAN_SUCCESS';
export const PASSPORT_TRAVEL_READINESS_DOCUMENT_SCAN_FALURE = 'PASSPORT_TRAVEL_READINESS_DOCUMENT_SCAN_FALURE';

// CHECKLIST SUBMISSIONS
export const POST_SUBMISSION = 'POST_SUBMISSION';
export const POST_SUBMISSION_SUCCESS = 'POST_SUBMISSION_SUCCESS';
export const POST_SUBMISSION_FAILURE = 'POST_SUBMISSION_FAILURE';
export const FETCH_SUBMISSION = 'FETCH_SUBMISSION';
export const FETCH_SUBMISSION_SUCCESS = 'FETCH_SUBMISSION_SUCCESS';
export const FETCH_SUBMISSION_FAILURE = 'FETCH_SUBMISSION_FAILURE';

// FILE UPLOAD
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
// FILE ATTACHMENTS
export const FETCH_ATTACHMENTS = 'FETCH_ATTACHMENTS';
export const FETCH_ATTACHMENTS_SUCCESS = 'FETCH_ATTACHMENTS_SUCCESS';
export const FETCH_ATTACHMENTS_FAILURE = 'FETCH_ATTACHMENTS_FAILURE';
export const DOWNLOAD_ATTACHMENTS = 'DOWNLOAD_ATTACHMENTS';
export const DOWNLOAD_ATTACHMENTS_SUCCESS = 'DOWNLOAD_ATTACHMENTS_SUCCESS';
export const DOWNLOAD_ATTACHMENTS_FAILURE = 'DOWNLOAD_ATTACHMENTS_FAILURE';

//TRAVEL READINESS DOCUMENTS
export const FETCH_ALL_USERS_READINESS_DOCUMENTS = 'FETCH_ALL_USERS_READINESS_DOCUMENTS';
export const FETCH_ALL_USERS_READINESS_DOCUMENTS_SUCCESS = 'FETCH_ALL_USERS_READINESS_DOCUMENTS_SUCCESS';
export const FETCH_ALL_USERS_READINESS_DOCUMENTS_FAILURE = 'FETCH_ALL_USERS_READINESS_DOCUMENTS_FAILURE';
export const FETCH_USER_READINESS_DOCUMENTS = 'FETCH_USER_READINESS_DOCUMENTS';
export const FETCH_USER_READINESS_DOCUMENTS_SUCCESS = 'FETCH_USER_READINESS_DOCUMENTS_SUCCESS';
export const FETCH_USER_READINESS_DOCUMENTS_FAILURE = 'FETCH_USER_READINESS_DOCUMENTS_FAILURE';
export const FETCH_TRAVEL_READINESS_DOCUMENT = 'FETCH_TRAVEL_READINESS_DOCUMENT';
export const FETCH_TRAVEL_READINESS_DOCUMENT_SUCCESS = 'FETCH_TRAVEL_READINESS_DOCUMENT_SUCCESS';
export const FETCH_TRAVEL_READINESS_DOCUMENT_FAILURE = 'FETCH_TRAVEL_READINESS_DOCUMENT_FAILURE';
export const VERIFY_TRAVEL_READINESS_DOCUMENT = 'VERIFY_TRAVEL_READINESS_DOCUMENT';
export const VERIFY_TRAVEL_READINESS_DOCUMENT_SUCCESS = 'VERIFY_TRAVEL_READINESS_DOCUMENT_SUCCESS';
export const VERIFY_TRAVEL_READINESS_DOCUMENT_FAILURE = 'VERIFY_TRAVEL_READINESS_DOCUMENT_FAILURE';
export const EDIT_TRAVEL_READINESS_DOCUMENT = 'EDIT_TRAVEL_READINESS_DOCUMENT';
export const EDIT_TRAVEL_READINESS_DOCUMENT_SUCCESS = 'EDIT_TRAVEL_READINESS_DOCUMENT_SUCCESS';
export const EDIT_TRAVEL_READINESS_DOCUMENT_FAILURE = 'EDIT_TRAVEL_READINESS_DOCUMENT_FAILURE';
export const DELETE_TRAVEL_READINESS_DOCUMENT = 'DELETE_TRAVEL_READINESS_DOCUMENT';
export const DELETE_TRAVEL_READINESS_DOCUMENT_SUCCESS = 'DELETE_TRAVEL_READINESS_DOCUMENT_SUCCESS';
export const DELETE_TRAVEL_READINESS_DOCUMENT_FAILURE = 'DELETE_TRAVEL_READINESS_DOCUMENT_FAILURE';


// TRAVELLING TEAMMATES
export const FETCH_TEAMMATES = 'FETCH_TEAMMATES';
export const FETCH_TEAMMATES_SUCCESS = 'FETCH_TEAMMATES_SUCCESS';
export const FETCH_TEAMMATES_FAILURE = 'FETCH_TEAMMATES_FAILURE';

// REMINDER SETUP
export const CREATE_REMINDER_EMAIL_TEMPLATE = 'CREATE_REMINDER_EMAIL_TEMPLATE';
export const CREATE_REMINDER_EMAIL_TEMPLATE_SUCCESS = 'CREATE_REMINDER_EMAIL_TEMPLATE_SUCCESS';
export const CREATE_REMINDER_EMAIL_TEMPLATE_FAILURE= 'CREATE_REMINDER_EMAIL_TEMPLATE_FAILURE';
export const FETCH_ALL_EMAIL_TEMPLATES = 'FETCH_ALL_EMAIL_TEMPLATES';
export const FETCH_ALL_EMAIL_TEMPLATES_SUCCESS = 'FETCH_ALL_EMAIL_TEMPLATES_SUCCESS';
export const FETCH_ALL_EMAIL_TEMPLATES_FAILURE = 'FETCH_ALL_EMAIL_TEMPLATES_FAILURE';
export const DISABLE_EMAIL_TEMPLATE = 'DISABLE_EMAIL_TEMPLATE';
export const DISABLE_EMAIL_TEMPLATE_SUCCESS = 'DISABLE_EMAIL_TEMPLATE_SUCCESS';
export const DISABLE_EMAIL_TEMPLATE_FAILURE = 'DISABLE_EMAIL_TEMPLATE_FAILURE';
export const FETCH_ONE_EMAIL_TEMPLATE = 'FETCH_ONE_EMAIL_TEMPLATE';
export const FETCH_ONE_EMAIL_TEMPLATE_SUCCESS = 'FETCH_ONE_EMAIL_TEMPLATE_SUCCESS';
export const FETCH_ONE_EMAIL_TEMPLATE_FAILURE = 'FETCH_ONE_EMAIL_TEMPLATE_FAILURE';
export const UPDATE_REMINDER_EMAIL_TEMPLATE = 'UPDATE_REMINDER_EMAIL_TEMPLATE';
export const UPDATE_REMINDER_EMAIL_TEMPLATE_SUCCESS = 'UPDATE_REMINDER_EMAIL_TEMPLATE_SUCCESS';
export const UPDATE_REMINDER_EMAIL_TEMPLATE_FAILURE = 'UPDATE_REMINDER_EMAIL_TEMPLATE_FAILURE';

// REMINDER CONDITIONS
export const CREATE_REMINDER = 'CREATE_REMINDER';
export const CREATE_REMINDER_SUCCESS = 'CREATE_REMINDER_SUCCESS';
export const CREATE_REMINDER_FAILURE = 'CREATE_REMINDER_FAILURE';
export const FETCH_TEMPLATE_DETAILS = 'FETCH_TEMPLATE_DETAILS';
export const ENABLE_REMINDER_EMAIL_TEMPLATE = 'ENABLE_REMINDER_EMAIL_TEMPLATE';
export const ENABLE_REMINDER_EMAIL_TEMPLATE_SUCCESS = 'ENABLE_REMINDER_EMAIL_TEMPLATE_SUCCESS';
export const ENABLE_REMINDER_EMAIL_TEMPLATE_FAILURE= 'ENABLE_REMINDER_EMAIL_TEMPLATE_FAILURE';
export const DISABLE_REMINDER_CONDITION = 'DISABLE_REMINDER_CONDITION';
export const DISABLE_REMINDER_CONDITION_SUCCESS = 'DISABLE_REMINDER_CONDITION_SUCCESS';
export const DISABLE_REMINDER_CONDITION_FAILURE = 'DISABLE_REMINDER_CONDITION_FAILURE';
export const FETCH_EMAIL_REMINDERS = 'FETCH_EMAIL_REMINDERS';
export const FETCH_EMAIL_REMINDERS_SUCCESS = 'FETCH_EMAIL_REMINDERS_SUCCESS';
export const FETCH_EMAIL_REMINDERS_FAILURE = 'FETCH_EMAIL_REMINDERS_FAILURE';
export const ENABLE_DISABLED_REMINDER_CONDITION = 'ENABLE_DISABLED_REMINDER_CONDITION';
export const ENABLE_DISABLED_REMINDER_CONDITION_SUCCESS = 'ENABLE_DISABLED_REMINDER_CONDITION_SUCCESS';
export const ENABLE_DISABLED_REMINDER_CONDITION_FAILURE = 'ENABLE_DISABLED_REMINDER_CONDITION_FAILURE';
export const EDIT_REMINDER = 'EDIT_REMINDER';
export const EDIT_REMINDER_SUCCESS = 'EDIT_REMINDER_SUCCESS';
export const EDIT_REMINDER_FAILURE = 'EDIT_REMINDER_FAILURE';
export const GET_SINGLE_REMINDER = 'GET_SINGLE_REMINDER';
export const GET_SINGLE_REMINDER_SUCCESS = 'GET_SINGLE_REMINDER_SUCCESS';
export const GET_SINGLE_REMINDER_FAILURE = 'GET_SINGLE_REMINDER_FAILURE';

// GET EMAILS
export const GET_ALL_EMAILS = 'GET_ALL_EMAILS';
export const GET_ALL_EMAILS_SUCCESS = 'GET_ALL_EMAILS_SUCCESS';
export const GET_ALL_EMAILS_FAILURE = 'GET_ALL_EMAILS_FAILURE';

// LIST TRAVEL REASONS
export const FETCH_TRAVEL_REASON = 'FETCH_TRAVEL_REASON';
export const FETCH_ALL_TRAVEL_REASONS = 'FETCH_ALL_TRAVEL_REASONS';
export const FETCH_ALL_TRAVEL_REASONS_SUCCESS = 'FETCH_ALL_TRAVEL_REASONS_SUCCESS';
export const FETCH_ALL_TRAVEL_REASONS_FAILURE = 'FETCH_ALL_TRAVEL_REASONS_FAILURE';

// TRAVEL REASONS
export const CREATE_TRAVEL_REASON = 'CREATE_TRAVEL_REASON';
export const CREATE_TRAVEL_REASON_SUCCESS = 'CREATE_TRAVEL_REASON_SUCCESS';
export const CREATE_TRAVEL_REASON_FAILURE = 'CREATE_TRAVEL_REASON_FAILURE';
export const VIEW_TRAVEL_REASON_DETAILS = 'VIEW_TRAVEL_REASON_DETAILS';
export const VIEW_TRAVEL_REASON_DETAILS_SUCCESS = 'VIEW_TRAVEL_REASON_DETAILS_SUCCESS';
export const VIEW_TRAVEL_REASON_DETAILS_FAILURE = 'VIEW_TRAVEL_REASON_DETAILS_FAILURE';
export const DELETE_TRAVEL_REASON = 'DELETE_TRAVEL_REASON';
export const DELETE_TRAVEL_REASON_SUCCESS = 'DELETE_TRAVEL_REASON_SUCCESS';
export const DELETE_TRAVEL_REASON_FAILURE = 'DELETE_TRAVEL_REASON_FAILURE';

// EDIT TRAVEL REASONS
export const EDIT_TRAVEL_REASON = 'EDIT_TRAVEL_REASON';
export const EDIT_TRAVEL_REASON_SUCCESS = 'EDIT_TRAVEL_REASON_SUCCESS';
export const EDIT_TRAVEL_REASON_FAILURE = 'EDIT_TRAVEL_REASON_FAILURE';
//TRAVEL STIPENDS
export const FETCH_ALL_TRAVEL_STIPENDS = 'FETCH_ALL_TRAVEL_STIPENDS';
export const FETCH_ALL_TRAVEL_STIPENDS_SUCCESS = 'FETCH_ALL_TRAVEL_STIPENDS_SUCCESS';
export const FETCH_ALL_TRAVEL_STIPENDS_FAILURE = 'FETCH_ALL_TRAVEL_STIPENDS_FAILURE';
export const CREATE_TRAVEL_STIPEND = 'CREATE_TRAVEL_STIPEND';
export const CREATE_TRAVEL_STIPEND_SUCCESS = 'CREATE_TRAVEL_STIPEND_SUCCESS';
export const CREATE_TRAVEL_STIPEND_FAILURE = 'CREATE_TRAVEL_STIPEND_FAILURE';
export const DELETE_TRAVEL_STIPEND = 'DELETE_TRAVEL_STIPEND';
export const DELETE_TRAVEL_STIPEND_SUCCESS = 'DELETE_TRAVEL_STIPEND_SUCCESS';
export const DELETE_TRAVEL_STIPEND_FAILURE = 'DELETE_TRAVEL_STIPEND_FAILURE';
export const FETCH_SINGLE_TRAVEL_STIPEND = 'FETCH_SINGLE_TRAVEL_STIPEND';
export const EDIT_TRAVEL_STIPEND = 'EDIT_TRAVEL_STIPEND';
export const EDIT_TRAVEL_STIPEND_SUCCESS = 'EDIT_TRAVEL_STIPEND_SUCCESS';
export const EDIT_TRAVEL_STIPEND_FAILURE = 'EDIT_TRAVEL_STIPEND_FAILURE';

//TRAVEL COSTS
export const FETCH_TRAVEL_COSTS_BY_LOCATION = 'FETCH_TRAVEL_COSTS_BY_LOCATION';
export const FETCH_TRAVEL_COSTS_BY_LOCATION_SUCCESS = 'FETCH_TRAVEL_COSTS_BY_LOCATION_SUCCESS';
export const FETCH_TRAVEL_COSTS_BY_LOCATION_FAILURE = 'FETCH_TRAVEL_COSTS_BY_LOCATION_FAILURE';

// HOTEL ESTIMATES
export const FETCH_ALL_HOTEL_ESTIMATES = 'FETCH_ALL_HOTEL_ESTIMATES';
export const FETCH_ALL_HOTEL_ESTIMATES_SUCCESS = 'FETCH_ALL_HOTEL_ESTIMATES_SUCCESS';
export const FETCH_ALL_HOTEL_ESTIMATES_FAILURE = 'FETCH_ALL_HOTEL_ESTIMATES_FAILURE';
export const FETCH_SINGLE_HOTEL_ESTIMATE = 'FETCH_SINGLE_HOTEL_ESTIMATE';
export const CREATE_HOTEL_ESTIMATE = 'CREATE_HOTEL_ESTIMATE';
export const CREATE_HOTEL_ESTIMATE_SUCCESS = 'CREATE_HOTEL_ESTIMATE_SUCCESS';
export const CREATE_HOTEL_ESTIMATE_FAILURE = 'CREATE_HOTEL_ESTIMATE_FAILURE';
export const UPDATE_HOTEL_ESTIMATE = 'UPDATE_HOTEL_ESTIMATE';
export const UPDATE_HOTEL_ESTIMATE_SUCCESS = 'UPDATE_HOTEL_ESTIMATE_SUCCESS';
export const UPDATE_HOTEL_ESTIMATE_FAILURE = 'UPDATE_HOTEL_ESTIMATE_FAILURE';
export const DELETE_HOTEL_ESTIMATE = 'DELETE_HOTEL_ESTIMATE';
export const DELETE_HOTEL_ESTIMATE_SUCCESS = 'DELETE_HOTEL_ESTIMATE_SUCCESS';
export const DELETE_HOTEL_ESTIMATE_FAILURE = 'DELETE_HOTEL_ESTIMATE_FAILURE';



// Approve Budget
export const UPDATE_BUDGET_STATUS = 'UPDATE_BUDGET_STATUS';
export const UPDATE_BUDGET_STATUS_SUCCESS = 'UPDATE_BUDGET_STATUS_SUCCESS';
export const UPDATE_BUDGET_STATUS_FAILURE = 'UPDATE_BUDGET_STATUS_FAILURE';


export const GET_ALL_DEPARTMENT = 'GET_ALL_DEPARTMENT';
export const GET_ALL_DEPARTMENT_SUCCESS = 'GET_ALL_DEPARTMENT_SUCCESS';
export const GET_ALL_DEPARTMENT_FAILURE = 'GET_ALL_DEPARTMENT_FAILURE';

export const RESET_ERROR_MESSAGES = 'RESET_ERROR_MESSAGES';

//TRAVEL REGIONS
export const ADD_REGION = 'ADD_REGION';
export const ADD_REGION_SUCCESS = 'ADD_REGION_SUCCESS';
export const ADD_REGION_FAILURE = 'ADD_REGION_FAILURE';
export const GET_REGION = 'GET_REGION';
export const GET_REGION_SUCCESS = 'GET_REGION_SUCCESS';
export const GET_REGION_FAILURE = 'GET_REGION_FAILURE';
//Countries
export const CREATE_COUNTRY = 'CREATE_COUNTRY';
export const CREATE_COUNTRY_SUCCESS = 'CREATE_COUNTRY_SUCCESS';
export const CREATE_COUNTRY_FAILURE = 'CREATE_COUNTRY_FAILURE';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILURE = 'GET_COUNTRIES_FAILURE';

// TRIP MODIFICATIONS
export const SUBMIT_MODIFICATION_REQUEST = 'SUBMIT_MODIFICATION_REQUEST';
export const FETCH_MODIFICATION_REQUEST = 'FETCH_MODIFICATION_REQUEST';
export const UPDATE_MODIFICATION_REQUEST = 'UPDATE_MODIFICATION_REQUEST';

//HELP RESOURCES
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const ADD_RESOURCE_FAILURE = 'ADD_RESOURCE_FAILURE';
export const GET_RESOURCE = 'GET_RESOURCE';
export const GET_RESOURCE_SUCCESS = 'GET_RESOURCE_SUCCESS';
export const GET_RESOURCE_FAILURE = 'GET_RESOURCE_FAILURE';

// FLIGHT ESTIMATES
export const CREATE_FLIGHT_ESTIMATE = 'CREATE_FLIGHT_ESTIMATE';
export const CREATE_FLIGHT_ESTIMATE_SUCCESS = 'CREATE_FLIGHT_ESTIMATE_SUCCESS';
export const CREATE_FLIGHT_ESTIMATE_FAILURE = 'CREATE_FLIGHT_ESTIMATE_FAILURE';
export const FETCH_ALL_FLIGHT_ESTIMATES = 'FETCH_ALL_FLIGHT_ESTIMATES';
export const FETCH_ALL_FLIGHT_ESTIMATES_SUCCESS = 'FETCH_ALL_FLIGHT_ESTIMATES_SUCCESS';
export const FETCH_ALL_FLIGHT_ESTIMATES_FAILURE = 'FETCH_ALL_FLIGHT_ESTIMATES_FAILURE';
export const FETCH_SINGLE_FLIGHT_ESTIMATE = 'FETCH_SINGLE_FLIGHT_ESTIMATE';
export const EDIT_FLIGHT_ESTIMATE = 'EDIT_FLIGHT_ESTIMATE';
export const EDIT_FLIGHT_ESTIMATE_SUCCESS = 'EDIT_FLIGHT_ESTIMATE_SUCCESS';
export const EDIT_FLIGHT_ESTIMATE_FAILURE = 'EDIT_FLIGHT_ESTIMATE_FAILURE';
export const DELETE_FLIGHT_ESTIMATE = 'DELETE_FLIGHT_ESTIMATE';
export const DELETE_FLIGHT_ESTIMATE_SUCCESS = 'DELETE_FLIGHT_ESTIMATE_SUCCESS';
export const DELETE_FLIGHT_ESTIMATE_FAILURE = 'DELETE_FLIGHT_ESTIMATE_FAILURE';

// dynamic checklist wizard
export const GET_ALL_DYNAMIC_CHECKLISTS = 'GET_ALL_DYNAMIC_CHECKLISTS';
export const GET_ALL_DYNAMIC_CHECKLISTS_SUCCESS = 'GET_ALL_DYNAMIC_CHECKLISTS_SUCCESS';
export const GET_ALL_DYNAMIC_CHECKLISTS_FAILURE = 'GET_ALL_DYNAMIC_CHECKLISTS_FAILURE';
export const UPDATE_NATIONALITY = 'UPDATE_NATIONALITY,';
export const UPDATE_NATIONALITY_SUCCESS = 'UPDATE_NATIONALITY_SUCCESS,';
export const UPDATE_DESTINATION = 'UPDATE_DESTINATION,';
export const UPDATE_DESTINATION_SUCCESS = 'UPDATE_DESTINATION_SUCCESS,';
export const ADD_NEW_CHECKLIST_ITEM = 'ADD_NEW_CHECKLIST_ITEM,';
export const ADD_NEW_CHECKLIST_ITEM_SUCCESS = 'ADD_NEW_CHECKLIST_ITEM_SUCCESS,';
export const ADD_QUESTION = 'ADD_QUESTION,';
export const DELETE_QUESTION = 'DELETE_QUESTION,';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS,';
export const UPDATE_BEHAVIOUR = 'UPDATE_BEHAVIOUR,';
export const UPDATE_BEHAVIOUR_SUCCESS = 'UPDATE_BEHAVIOUR_SUCCESS,';
export const HANDLE_ITEMS = 'HANDLE_ITEMS,';
export const HANDLE_ITEMS_SUCCESS = 'HANDLE_ITEMS_SUCCESS,';
export const DELETE_ITEM = 'DELETE_ITEM,';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS,';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS,';
export const CREATE_DYNAMIC_CHECKLIST = 'CREATE_DYNAMIC_CHECKLIST,';
export const CREATE_DYNAMIC_CHECKLIST_SUCCESS = 'CREATE_DYNAMIC_CHECKLIST_SUCCESS';
export const UNDO_DYNAMIC_CHECKLIST = 'UNDO_DYNAMIC_CHECKLIST';
export const REDO_DYNAMIC_CHECKLIST = 'REDO_DYNAMIC_CHECKLIST';
export const RESET_DYNAMIC_CHECKLIST = 'RESET_DYNAMIC_CHECKLIST';
export const GET_ONE_CHECKLIST = 'GET_ONE_CHECKLIST';
export const GET_ONE_CHECKLIST_SUCCESS = 'GET_ONE_CHECKLIST_SUCCESS';
export const GET_ONE_CHECKLIST_FAILURE = 'GET_ONE_CHECKLIST_FAILURE';
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST';
export const DELETE_CHECKLIST_SUCCESS = 'DELETE_CHECKLIST_SUCCESS';
export const DELETE_CHECKLIST_FAILURE = 'DELETE_CHECKLIST_FAILURE';
export const GET_DELETED_CHECKLISTS = 'GET_DELETED_CHECKLISTS';
export const GET_ALL_DELETED_CHECKLISTS_SUCCESS = 'GET_ALL_DELETED_CHECKLISTS_SUCCESS';
export const RESTORE_CHECKLIST = 'RESTORE_CHECKLIST';
export const RESTORE_CHECKLIST_SUCCESS = 'RESTORE_CHECKLIST_SUCCESS';
export const RESTORE_CHECKLIST_FAILURE = 'RESTORE_CHECKLIST_FAILURE';
export const RESTORE_ALL_CHECKLISTS = 'RESTORE_ALL_CHECKLISTS';
export const RESTORE_ALL_CHECKLISTS_SUCCESS = 'RESTORE_ALL_CHECKLISTS_SUCCESS';
export const RESTORE_ALL_CHECKLISTS_FAILURE = 'RESTORE_ALL_CHECKLISTS_FAILURE';
export const GET_SINGLE_CHECKLIST = 'GET_SINGLE_CHECKLIST';
export const GET_SINGLE_CHECKLIST_SUCCESS = 'GET_SINGLE_CHECKLIST_SUCCESS';
export const UPDATE_CHECKLIST = 'UPDATE_CHECKLIST';
export const UPDATE_CHECKLIST_SUCCESS = 'UPDATE_CHECKLIST_SUCCESS';
export const GET_CHECKLIST_FROM_STORAGE = 'GET_CHECKLIST_FROM_STORAGE';
export const GET_CHECKLIST_FROM_STORAGE_SUCCESS = 'GET_CHECKLIST_FROM_STORAGE_SUCCESS';

// NO PASSPORT
export const ADD_NO_PASSPORT_NOTIFICATION = 'ADD_NO_PASSPORT_NOTIFICATION';
export const ADD_NO_PASSPORT_NOTIFICATION_SUCCESS = 'ADD_NO_PASSPORT_NOTIFICATION_SUCCESS';
export const ADD_NO_PASSPORT_NOTIFICATION_FAILURE = 'ADD_NO_PASSPORT_NOTIFICATION_FAILURE';


// ERROR BOUNDARY
export const REPORT_CRASH = 'REPORT_CRASH';
